language: c
compiler:
 - gcc
 - clang
env:
  global:
   - secure: "fceMvf+o/Jmz19H/jJA3GRF+oW4jnRGq+mpzE4AuoKTfIN0ppDtcVigWR3WPW9LydAQROUIxjgf2qXy/TnxwPtnZpBuMDIIjoNEBpEncHPwnDTOhCEu804005/o/qpmj10NMC1y0WRdd7fBP+2ZydQvwSO1wYG7Ut0wBsXqgzlavnrbsh2GcmzERVm0VHaV/Jiw0uLpz3gcCk/bgYt1poNrH9P2i62ze0Xiqtf1jkrkNGP6IiNKP3Udge4hwJZaqEZLGKqc4LAhWlYmH/MldxJYyVm4Uh/dCgYClRHEUWgxcWP2CRJi5RwJ2MdHkzVSVui23gTeI6rQIEOkbBhWQSfFCDHpystQnHkkx9FsJou4LtwxYUP36VBfTfM9lKYquF0i7H3u2QZCEPpzK3TgQb73KZrcE7pbGyCjIqzklA0x3rhGASTXY/z82AgP/DSEqBBKswtoR7ahiXOg7HjZw8XHGtTMwcIKnkJCc7Jy9fNHyWmcmJFLpaGVvaxqX9MODQiLhC6pot7yAN89Z22hjOIbnU58kDXFSXspDP0OrVR4HD11m/38An6KXCXN1WMdLxqdx/MsBkZVuv5KruHFkRG/WiTURpg3ykW2fRv//pishNm5cRdwi73w2ORhDy8nBVvwKnMGyjMxcVLZBBIARQcPSbkFgH7v5zOhU9Qw2+ak="
addons:
  coverity_scan:
    project:
      name: "lxc/lxc"
      description: "LXC - Linux Containers https://linuxcontainers.org/lxc"
    notification_email: lxc-devel@lists.linuxcontainers.org
    build_command_prepend: "./autogen.sh && rm -Rf build && mkdir build && cd build && ../configure --enable-tests --with-distro=unknown"
    build_command: "make -j4"
    branch_pattern: coverity
before_install:
 - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
 - sudo add-apt-repository ppa:ubuntu-lxc/daily -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libapparmor-dev libcap-dev libseccomp-dev python3-dev python3-setuptools docbook2x libgnutls-dev libselinux1-dev linux-libc-dev
script:
 - ./autogen.sh
 - rm -Rf build
 - mkdir build
 - cd build
 - ../configure --enable-tests --with-distro=unknown
 - make -j4
 - make DESTDIR=$TRAVIS_BUILD_DIR/install install
notifications:
  email:
    recipients:
      - lxc-devel@lists.linuxcontainers.org
  webhooks: https://linuxcontainers.org/webhook-lxcbot/
